#!/bin/bash

# Product Folder Creation Script
# Creates 1000 product folders organized by categories and subcategories

BASE_DIR="/Users/murali/Projects/GitCode/topiko-platform/images/products"

echo "Creating expanded product folder structure..."

# FASHION CATEGORY (250 products)
echo "Creating Fashion folders..."

# Men's Clothing - Shirts (15 products)
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/formal-white-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/formal-blue-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/formal-black-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/formal-grey-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/formal-striped-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/casual-checkered-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/casual-denim-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/casual-linen-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/casual-printed-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/casual-plain-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/party-wear-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/silk-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/cotton-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/half-sleeve-shirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/shirts/mandarin-collar-shirt"

# Men's Clothing - T-Shirts (10 products)
mkdir -p "$BASE_DIR/fashion/mens-clothing/tshirts/polo-navy-blue"
mkdir -p "$BASE_DIR/fashion/mens-clothing/tshirts/polo-white"
mkdir -p "$BASE_DIR/fashion/mens-clothing/tshirts/round-neck-black"
mkdir -p "$BASE_DIR/fashion/mens-clothing/tshirts/round-neck-grey"
mkdir -p "$BASE_DIR/fashion/mens-clothing/tshirts/v-neck-blue"
mkdir -p "$BASE_DIR/fashion/mens-clothing/tshirts/graphic-red"
mkdir -p "$BASE_DIR/fashion/mens-clothing/tshirts/henley-green"
mkdir -p "$BASE_DIR/fashion/mens-clothing/tshirts/full-sleeve-tshirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/tshirts/oversized-tshirt"
mkdir -p "$BASE_DIR/fashion/mens-clothing/tshirts/sports-tshirt"

# Men's Clothing - Jeans & Trousers (10 products)
mkdir -p "$BASE_DIR/fashion/mens-clothing/jeans/slim-fit-blue"
mkdir -p "$BASE_DIR/fashion/mens-clothing/jeans/regular-fit-black"
mkdir -p "$BASE_DIR/fashion/mens-clothing/jeans/skinny-grey"
mkdir -p "$BASE_DIR/fashion/mens-clothing/jeans/ripped-jeans"
mkdir -p "$BASE_DIR/fashion/mens-clothing/jeans/bootcut-jeans"
mkdir -p "$BASE_DIR/fashion/mens-clothing/trousers/formal-black"
mkdir -p "$BASE_DIR/fashion/mens-clothing/trousers/formal-navy"
mkdir -p "$BASE_DIR/fashion/mens-clothing/trousers/formal-grey"
mkdir -p "$BASE_DIR/fashion/mens-clothing/trousers/chinos-beige"
mkdir -p "$BASE_DIR/fashion/mens-clothing/trousers/cargo-khaki"

# Men's Clothing - Ethnic Wear (10 products)
mkdir -p "$BASE_DIR/fashion/mens-clothing/ethnic/kurta-white-cotton"
mkdir -p "$BASE_DIR/fashion/mens-clothing/ethnic/kurta-blue-silk"
mkdir -p "$BASE_DIR/fashion/mens-clothing/ethnic/kurta-pajama-set"
mkdir -p "$BASE_DIR/fashion/mens-clothing/ethnic/sherwani-golden"
mkdir -p "$BASE_DIR/fashion/mens-clothing/ethnic/nehru-jacket-black"
mkdir -p "$BASE_DIR/fashion/mens-clothing/ethnic/dhoti-white"
mkdir -p "$BASE_DIR/fashion/mens-clothing/ethnic/pathani-suit"
mkdir -p "$BASE_DIR/fashion/mens-clothing/ethnic/bandhgala-suit"
mkdir -p "$BASE_DIR/fashion/mens-clothing/ethnic/modi-jacket"
mkdir -p "$BASE_DIR/fashion/mens-clothing/ethnic/lungi-cotton"

# Men's Clothing - Winter Wear (10 products)
mkdir -p "$BASE_DIR/fashion/mens-clothing/winter/sweater-wool-navy"
mkdir -p "$BASE_DIR/fashion/mens-clothing/winter/sweater-cable-knit"
mkdir -p "$BASE_DIR/fashion/mens-clothing/winter/hoodie-black"
mkdir -p "$BASE_DIR/fashion/mens-clothing/winter/hoodie-grey"
mkdir -p "$BASE_DIR/fashion/mens-clothing/winter/sweatshirt-blue"
mkdir -p "$BASE_DIR/fashion/mens-clothing/winter/jacket-leather-black"
mkdir -p "$BASE_DIR/fashion/mens-clothing/winter/jacket-denim"
mkdir -p "$BASE_DIR/fashion/mens-clothing/winter/jacket-bomber"
mkdir -p "$BASE_DIR/fashion/mens-clothing/winter/windcheater-red"
mkdir -p "$BASE_DIR/fashion/mens-clothing/winter/blazer-navy"

# Women's Clothing - Sarees (15 products)
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/silk-red-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/cotton-blue-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/georgette-pink-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/chiffon-yellow-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/banarasi-gold-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/kanjivaram-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/designer-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/printed-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/embroidered-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/party-wear-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/casual-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/wedding-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/half-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/net-saree"
mkdir -p "$BASE_DIR/fashion/womens-clothing/sarees/organza-saree"

# Women's Clothing - Kurtis & Suits (15 products)
mkdir -p "$BASE_DIR/fashion/womens-clothing/kurtis/cotton-white-kurti"
mkdir -p "$BASE_DIR/fashion/womens-clothing/kurtis/printed-blue-kurti"
mkdir -p "$BASE_DIR/fashion/womens-clothing/kurtis/embroidered-kurti"
mkdir -p "$BASE_DIR/fashion/womens-clothing/kurtis/long-black-kurti"
mkdir -p "$BASE_DIR/fashion/womens-clothing/kurtis/short-red-kurti"
mkdir -p "$BASE_DIR/fashion/womens-clothing/kurtis/anarkali-kurti"
mkdir -p "$BASE_DIR/fashion/womens-clothing/kurtis/straight-kurti"
mkdir -p "$BASE_DIR/fashion/womens-clothing/kurtis/a-line-kurti"
mkdir -p "$BASE_DIR/fashion/womens-clothing/suits/salwar-kameez"
mkdir -p "$BASE_DIR/fashion/womens-clothing/suits/churidar-suit"
mkdir -p "$BASE_DIR/fashion/womens-clothing/suits/patiala-suit"
mkdir -p "$BASE_DIR/fashion/womens-clothing/suits/anarkali-suit"
mkdir -p "$BASE_DIR/fashion/womens-clothing/suits/palazzo-suit"
mkdir -p "$BASE_DIR/fashion/womens-clothing/suits/sharara-suit"
mkdir -p "$BASE_DIR/fashion/womens-clothing/suits/gharara-suit"

# Women's Clothing - Lehenga (10 products)
mkdir -p "$BASE_DIR/fashion/womens-clothing/lehenga/bridal-red-lehenga"
mkdir -p "$BASE_DIR/fashion/womens-clothing/lehenga/designer-pink-lehenga"
mkdir -p "$BASE_DIR/fashion/womens-clothing/lehenga/party-blue-lehenga"
mkdir -p "$BASE_DIR/fashion/womens-clothing/lehenga/wedding-golden-lehenga"
mkdir -p "$BASE_DIR/fashion/womens-clothing/lehenga/crop-top-lehenga"
mkdir -p "$BASE_DIR/fashion/womens-clothing/lehenga/jacket-lehenga"
mkdir -p "$BASE_DIR/fashion/womens-clothing/lehenga/printed-lehenga"
mkdir -p "$BASE_DIR/fashion/womens-clothing/lehenga/embroidered-lehenga"
mkdir -p "$BASE_DIR/fashion/womens-clothing/lehenga/silk-lehenga"
mkdir -p "$BASE_DIR/fashion/womens-clothing/lehenga/net-lehenga"

# Women's Clothing - Western Wear (20 products)
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/top-casual-white"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/top-formal-black"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/crop-top-pink"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/tunic-blue"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/off-shoulder-top"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/shirt-formal-white"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/shirt-denim"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/tshirt-grey"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/dress-maxi-floral"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/dress-bodycon-black"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/dress-aline-blue"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/jumpsuit-denim"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/jeans-blue"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/jeans-black"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/jeggings-black"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/palazzo-printed"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/skirt-pencil-black"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/skirt-aline-blue"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/shorts-denim"
mkdir -p "$BASE_DIR/fashion/womens-clothing/western/blazer-formal"

# Kids Clothing - Boys (20 products)
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/tshirt-spiderman"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/tshirt-batman"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/shirt-checked"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/shirt-plain"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/jeans-blue"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/shorts-khaki"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/tracksuit-sports"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/kurta-white"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/sherwani-kids"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/blazer-black"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/school-uniform-shirt"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/school-uniform-pant"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/sweater-blue"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/jacket-winter"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/raincoat-yellow"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/nightsuit-printed"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/thermal-set"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/swimming-trunk"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/romper-baby"
mkdir -p "$BASE_DIR/fashion/kids-clothing/boys/onesie-pack"

# Kids Clothing - Girls (20 products)
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/frock-party-pink"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/frock-casual-blue"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/frock-printed"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/top-embroidered"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/legging-black"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/jeans-denim"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/skirt-pleated"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/lehenga-kids"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/anarkali-kids"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/kurti-set"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/school-uniform"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/sweater-pink"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/jacket-winter"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/raincoat-printed"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/nightsuit-cotton"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/thermal-set"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/swimming-costume"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/romper-baby"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/onesie-cute"
mkdir -p "$BASE_DIR/fashion/kids-clothing/girls/dungaree-denim"

# Fashion Accessories (40 products)
mkdir -p "$BASE_DIR/fashion/accessories/belts/leather-black-belt"
mkdir -p "$BASE_DIR/fashion/accessories/belts/leather-brown-belt"
mkdir -p "$BASE_DIR/fashion/accessories/belts/formal-belt"
mkdir -p "$BASE_DIR/fashion/accessories/belts/casual-belt"
mkdir -p "$BASE_DIR/fashion/accessories/belts/chain-belt"
mkdir -p "$BASE_DIR/fashion/accessories/ties/silk-blue-tie"
mkdir -p "$BASE_DIR/fashion/accessories/ties/red-tie"
mkdir -p "$BASE_DIR/fashion/accessories/ties/bow-tie-black"
mkdir -p "$BASE_DIR/fashion/accessories/wallets/leather-wallet-mens"
mkdir -p "$BASE_DIR/fashion/accessories/wallets/canvas-wallet"
mkdir -p "$BASE_DIR/fashion/accessories/wallets/card-holder"
mkdir -p "$BASE_DIR/fashion/accessories/wallets/womens-wallet"
mkdir -p "$BASE_DIR/fashion/accessories/watches/analog-watch-mens"
mkdir -p "$BASE_DIR/fashion/accessories/watches/digital-watch"
mkdir -p "$BASE_DIR/fashion/accessories/watches/smart-watch"
mkdir -p "$BASE_DIR/fashion/accessories/watches/womens-watch"
mkdir -p "$BASE_DIR/fashion/accessories/sunglasses/aviator-sunglasses"
mkdir -p "$BASE_DIR/fashion/accessories/sunglasses/wayfarer-sunglasses"
mkdir -p "$BASE_DIR/fashion/accessories/sunglasses/cat-eye-sunglasses"
mkdir -p "$BASE_DIR/fashion/accessories/sunglasses/sports-sunglasses"
mkdir -p "$BASE_DIR/fashion/accessories/bags/handbag-tote"
mkdir -p "$BASE_DIR/fashion/accessories/bags/satchel-bag"
mkdir -p "$BASE_DIR/fashion/accessories/bags/clutch-gold"
mkdir -p "$BASE_DIR/fashion/accessories/bags/backpack-leather"
mkdir -p "$BASE_DIR/fashion/accessories/bags/laptop-bag"
mkdir -p "$BASE_DIR/fashion/accessories/bags/duffle-bag"
mkdir -p "$BASE_DIR/fashion/accessories/bags/sling-bag"
mkdir -p "$BASE_DIR/fashion/accessories/jewelry/earrings-studs"
mkdir -p "$BASE_DIR/fashion/accessories/jewelry/earrings-hoops"
mkdir -p "$BASE_DIR/fashion/accessories/jewelry/necklace-chain"
mkdir -p "$BASE_DIR/fashion/accessories/jewelry/bracelet-charm"
mkdir -p "$BASE_DIR/fashion/accessories/jewelry/anklet-silver"
mkdir -p "$BASE_DIR/fashion/accessories/jewelry/ring-fashion"
mkdir -p "$BASE_DIR/fashion/accessories/caps/baseball-cap"
mkdir -p "$BASE_DIR/fashion/accessories/caps/fedora-hat"
mkdir -p "$BASE_DIR/fashion/accessories/scarves/wool-scarf"
mkdir -p "$BASE_DIR/fashion/accessories/scarves/silk-stole"
mkdir -p "$BASE_DIR/fashion/accessories/socks/formal-socks"
mkdir -p "$BASE_DIR/fashion/accessories/socks/sports-socks"
mkdir -p "$BASE_DIR/fashion/accessories/socks/ankle-socks"

# ELECTRONICS CATEGORY (150 products)
echo "Creating Electronics folders..."

# Mobile Phones (30 products)
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/iphone-15-pro"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/iphone-14"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/samsung-s24-ultra"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/samsung-a54"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/oneplus-12"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/oneplus-nord"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/xiaomi-14"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/redmi-note-13"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/realme-11-pro"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/oppo-reno-11"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/vivo-v29"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/nothing-phone-2"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/pixel-8-pro"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/motorola-edge"
mkdir -p "$BASE_DIR/electronics/mobiles/smartphones/nokia-g42"
mkdir -p "$BASE_DIR/electronics/mobiles/tablets/ipad-pro-m2"
mkdir -p "$BASE_DIR/electronics/mobiles/tablets/ipad-air"
mkdir -p "$BASE_DIR/electronics/mobiles/tablets/ipad-mini"
mkdir -p "$BASE_DIR/electronics/mobiles/tablets/samsung-tab-s9"
mkdir -p "$BASE_DIR/electronics/mobiles/tablets/lenovo-tab"
mkdir -p "$BASE_DIR/electronics/mobiles/accessories/phone-case-clear"
mkdir -p "$BASE_DIR/electronics/mobiles/accessories/phone-case-leather"
mkdir -p "$BASE_DIR/electronics/mobiles/accessories/screen-guard-tempered"
mkdir -p "$BASE_DIR/electronics/mobiles/accessories/charger-fast"
mkdir -p "$BASE_DIR/electronics/mobiles/accessories/charger-wireless"
mkdir -p "$BASE_DIR/electronics/mobiles/accessories/power-bank-10000"
mkdir -p "$BASE_DIR/electronics/mobiles/accessories/power-bank-20000"
mkdir -p "$BASE_DIR/electronics/mobiles/accessories/earbuds-tws"
mkdir -p "$BASE_DIR/electronics/mobiles/accessories/selfie-stick"
mkdir -p "$BASE_DIR/electronics/mobiles/accessories/car-holder"

# Laptops & Computers (30 products)
mkdir -p "$BASE_DIR/electronics/laptops/gaming/asus-rog-strix"
mkdir -p "$BASE_DIR/electronics/laptops/gaming/msi-gaming"
mkdir -p "$BASE_DIR/electronics/laptops/gaming/hp-omen"
mkdir -p "$BASE_DIR/electronics/laptops/business/dell-xps-13"
mkdir -p "$BASE_DIR/electronics/laptops/business/lenovo-thinkpad"
mkdir -p "$BASE_DIR/electronics/laptops/business/hp-elitebook"
mkdir -p "$BASE_DIR/electronics/laptops/macbooks/macbook-pro-16"
mkdir -p "$BASE_DIR/electronics/laptops/macbooks/macbook-air-m2"
mkdir -p "$BASE_DIR/electronics/laptops/macbooks/macbook-pro-14"
mkdir -p "$BASE_DIR/electronics/laptops/budget/hp-pavilion"
mkdir -p "$BASE_DIR/electronics/laptops/budget/asus-vivobook"
mkdir -p "$BASE_DIR/electronics/laptops/budget/lenovo-ideapad"
mkdir -p "$BASE_DIR/electronics/laptops/2in1/surface-pro-9"
mkdir -p "$BASE_DIR/electronics/laptops/2in1/hp-spectre"
mkdir -p "$BASE_DIR/electronics/laptops/2in1/lenovo-yoga"
mkdir -p "$BASE_DIR/electronics/computers/desktops/gaming-pc-custom"
mkdir -p "$BASE_DIR/electronics/computers/desktops/imac-24"
mkdir -p "$BASE_DIR/electronics/computers/desktops/dell-optiplex"
mkdir -p "$BASE_DIR/electronics/computers/peripherals/monitor-4k"
mkdir -p "$BASE_DIR/electronics/computers/peripherals/monitor-curved"
mkdir -p "$BASE_DIR/electronics/computers/peripherals/keyboard-mechanical"
mkdir -p "$BASE_DIR/electronics/computers/peripherals/mouse-gaming"
mkdir -p "$BASE_DIR/electronics/computers/peripherals/webcam-hd"
mkdir -p "$BASE_DIR/electronics/computers/peripherals/printer-laser"
mkdir -p "$BASE_DIR/electronics/computers/peripherals/scanner-flatbed"
mkdir -p "$BASE_DIR/electronics/computers/storage/ssd-1tb"
mkdir -p "$BASE_DIR/electronics/computers/storage/hard-drive-external"
mkdir -p "$BASE_DIR/electronics/computers/storage/pen-drive-64gb"
mkdir -p "$BASE_DIR/electronics/computers/storage/memory-card-128gb"
mkdir -p "$BASE_DIR/electronics/computers/networking/router-wifi6"

# Audio & Entertainment (30 products)
mkdir -p "$BASE_DIR/electronics/audio/headphones/sony-wh1000xm5"
mkdir -p "$BASE_DIR/electronics/audio/headphones/bose-qc45"
mkdir -p "$BASE_DIR/electronics/audio/headphones/airpods-pro"
mkdir -p "$BASE_DIR/electronics/audio/headphones/beats-studio"
mkdir -p "$BASE_DIR/electronics/audio/headphones/jbl-tune"
mkdir -p "$BASE_DIR/electronics/audio/earbuds/samsung-buds"
mkdir -p "$BASE_DIR/electronics/audio/earbuds/oneplus-buds"
mkdir -p "$BASE_DIR/electronics/audio/earbuds/realme-buds"
mkdir -p "$BASE_DIR/electronics/audio/earbuds/boat-airdopes"
mkdir -p "$BASE_DIR/electronics/audio/earbuds/noise-buds"
mkdir -p "$BASE_DIR/electronics/audio/speakers/jbl-flip-6"
mkdir -p "$BASE_DIR/electronics/audio/speakers/bose-soundlink"
mkdir -p "$BASE_DIR/electronics/audio/speakers/marshall-speaker"
mkdir -p "$BASE_DIR/electronics/audio/speakers/sony-portable"
mkdir -p "$BASE_DIR/electronics/audio/speakers/boat-stone"
mkdir -p "$BASE_DIR/electronics/audio/home-audio/soundbar-samsung"
mkdir -p "$BASE_DIR/electronics/audio/home-audio/home-theater-sony"
mkdir -p "$BASE_DIR/electronics/audio/home-audio/alexa-echo"
mkdir -p "$BASE_DIR/electronics/audio/home-audio/google-home"
mkdir -p "$BASE_DIR/electronics/audio/home-audio/amplifier-stereo"
mkdir -p "$BASE_DIR/electronics/tv/smart-tv/samsung-55-inch"
mkdir -p "$BASE_DIR/electronics/tv/smart-tv/lg-oled-65"
mkdir -p "$BASE_DIR/electronics/tv/smart-tv/sony-bravia-43"
mkdir -p "$BASE_DIR/electronics/tv/smart-tv/mi-tv-32"
mkdir -p "$BASE_DIR/electronics/tv/smart-tv/oneplus-tv-50"
mkdir -p "$BASE_DIR/electronics/tv/accessories/fire-tv-stick"
mkdir -p "$BASE_DIR/electronics/tv/accessories/chromecast"
mkdir -p "$BASE_DIR/electronics/tv/accessories/set-top-box"
mkdir -p "$BASE_DIR/electronics/tv/accessories/projector-4k"
mkdir -p "$BASE_DIR/electronics/tv/accessories/dvd-player"

# Gaming & Cameras (30 products)
mkdir -p "$BASE_DIR/electronics/gaming/consoles/playstation-5"
mkdir -p "$BASE_DIR/electronics/gaming/consoles/xbox-series-x"
mkdir -p "$BASE_DIR/electronics/gaming/consoles/nintendo-switch"
mkdir -p "$BASE_DIR/electronics/gaming/accessories/ps5-controller"
mkdir -p "$BASE_DIR/electronics/gaming/accessories/xbox-controller"
mkdir -p "$BASE_DIR/electronics/gaming/accessories/gaming-headset"
mkdir -p "$BASE_DIR/electronics/gaming/accessories/gaming-keyboard"
mkdir -p "$BASE_DIR/electronics/gaming/accessories/gaming-mouse"
mkdir -p "$BASE_DIR/electronics/gaming/accessories/gaming-chair"
mkdir -p "$BASE_DIR/electronics/gaming/accessories/steering-wheel"
mkdir -p "$BASE_DIR/electronics/cameras/dslr/canon-eos-r5"
mkdir -p "$BASE_DIR/electronics/cameras/dslr/nikon-d850"
mkdir -p "$BASE_DIR/electronics/cameras/dslr/sony-alpha"
mkdir -p "$BASE_DIR/electronics/cameras/mirrorless/fujifilm-xt5"
mkdir -p "$BASE_DIR/electronics/cameras/mirrorless/panasonic-lumix"
mkdir -p "$BASE_DIR/electronics/cameras/action/gopro-hero-12"
mkdir -p "$BASE_DIR/electronics/cameras/action/dji-action"
mkdir -p "$BASE_DIR/electronics/cameras/action/insta360"
mkdir -p "$BASE_DIR/electronics/cameras/instant/instax-mini"
mkdir -p "$BASE_DIR/electronics/cameras/instant/polaroid"
mkdir -p "$BASE_DIR/electronics/cameras/accessories/lens-wide-angle"
mkdir -p "$BASE_DIR/electronics/cameras/accessories/lens-telephoto"
mkdir -p "$BASE_DIR/electronics/cameras/accessories/tripod-professional"
mkdir -p "$BASE_DIR/electronics/cameras/accessories/gimbal-stabilizer"
mkdir -p "$BASE_DIR/electronics/cameras/accessories/camera-bag"
mkdir -p "$BASE_DIR/electronics/wearables/smartwatch/apple-watch-9"
mkdir -p "$BASE_DIR/electronics/wearables/smartwatch/samsung-galaxy-watch"
mkdir -p "$BASE_DIR/electronics/wearables/fitness/fitbit-charge"
mkdir -p "$BASE_DIR/electronics/wearables/fitness/mi-band-8"
mkdir -p "$BASE_DIR/electronics/wearables/vr/meta-quest-3"

# Home Appliances (30 products)
mkdir -p "$BASE_DIR/electronics/appliances/kitchen/refrigerator-lg-double"
mkdir -p "$BASE_DIR/electronics/appliances/kitchen/refrigerator-samsung-single"
mkdir -p "$BASE_DIR/electronics/appliances/kitchen/microwave-ifb"
mkdir -p "$BASE_DIR/electronics/appliances/kitchen/mixer-grinder-preethi"
mkdir -p "$BASE_DIR/electronics/appliances/kitchen/water-purifier-kent"
mkdir -p "$BASE_DIR/electronics/appliances/washing/washing-machine-front-load"
mkdir -p "$BASE_DIR/electronics/appliances/washing/washing-machine-top-load"
mkdir -p "$BASE_DIR/electronics/appliances/washing/dishwasher-bosch"
mkdir -p "$BASE_DIR/electronics/appliances/cooling/ac-split-1-5-ton"
mkdir -p "$BASE_DIR/electronics/appliances/cooling/ac-window"
mkdir -p "$BASE_DIR/electronics/appliances/cooling/air-cooler"
mkdir -p "$BASE_DIR/electronics/appliances/cooling/ceiling-fan"
mkdir -p "$BASE_DIR/electronics/appliances/cooling/table-fan"
mkdir -p "$BASE_DIR/electronics/appliances/cooling/exhaust-fan"
mkdir -p "$BASE_DIR/electronics/appliances/heating/room-heater"
mkdir -p "$BASE_DIR/electronics/appliances/heating/water-heater-geyser"
mkdir -p "$BASE_DIR/electronics/appliances/heating/induction-cooktop"
mkdir -p "$BASE_DIR/electronics/appliances/small/electric-kettle"
mkdir -p "$BASE_DIR/electronics/appliances/small/coffee-maker"
mkdir -p "$BASE_DIR/electronics/appliances/small/toaster"
mkdir -p "$BASE_DIR/electronics/appliances/small/sandwich-maker"
mkdir -p "$BASE_DIR/electronics/appliances/small/rice-cooker"
mkdir -p "$BASE_DIR/electronics/appliances/small/steam-iron"
mkdir -p "$BASE_DIR/electronics/appliances/small/vacuum-cleaner"
mkdir -p "$BASE_DIR/electronics/appliances/small/air-fryer"
mkdir -p "$BASE_DIR/electronics/appliances/small/juicer"
mkdir -p "$BASE_DIR/electronics/appliances/small/hand-blender"
mkdir -p "$BASE_DIR/electronics/appliances/small/food-processor"
mkdir -p "$BASE_DIR/electronics/appliances/small/egg-boiler"
mkdir -p "$BASE_DIR/electronics/appliances/small/hair-dryer"

# FOOD & BEVERAGES CATEGORY (150 products)
echo "Creating Food & Beverages folders..."

# Restaurant Food (40 products)
mkdir -p "$BASE_DIR/food/indian/north-indian/biryani-chicken"
mkdir -p "$BASE_DIR/food/indian/north-indian/biryani-mutton"
mkdir -p "$BASE_DIR/food/indian/north-indian/biryani-veg"
mkdir -p "$BASE_DIR/food/indian/north-indian/butter-chicken"
mkdir -p "$BASE_DIR/food/indian/north-indian/dal-makhani"
mkdir -p "$BASE_DIR/food/indian/north-indian/paneer-butter-masala"
mkdir -p "$BASE_DIR/food/indian/north-indian/chole-bhature"
mkdir -p "$BASE_DIR/food/indian/north-indian/rajma-chawal"
mkdir -p "$BASE_DIR/food/indian/north-indian/kadai-paneer"
mkdir -p "$BASE_DIR/food/indian/north-indian/naan-roti"
mkdir -p "$BASE_DIR/food/indian/south-indian/dosa-masala"
mkdir -p "$BASE_DIR/food/indian/south-indian/idli-sambar"
mkdir -p "$BASE_DIR/food/indian/south-indian/vada-sambar"
mkdir -p "$BASE_DIR/food/indian/south-indian/uttapam"
mkdir -p "$BASE_DIR/food/indian/south-indian/pongal"
mkdir -p "$BASE_DIR/food/indian/south-indian/rasam-rice"
mkdir -p "$BASE_DIR/food/indian/south-indian/curd-rice"
mkdir -p "$BASE_DIR/food/indian/south-indian/appam"
mkdir -p "$BASE_DIR/food/indian/street-food/pav-bhaji"
mkdir -p "$BASE_DIR/food/indian/street-food/vada-pav"
mkdir -p "$BASE_DIR/food/indian/street-food/bhel-puri"
mkdir -p "$BASE_DIR/food/indian/street-food/pani-puri"
mkdir -p "$BASE_DIR/food/indian/street-food/samosa"
mkdir -p "$BASE_DIR/food/indian/street-food/kachori"
mkdir -p "$BASE_DIR/food/indian/street-food/momos-veg"
mkdir -p "$BASE_DIR/food/indian/street-food/momos-chicken"
mkdir -p "$BASE_DIR/food/indian/tandoor/tandoori-chicken"
mkdir -p "$BASE_DIR/food/indian/tandoor/chicken-tikka"
mkdir -p "$BASE_DIR/food/indian/tandoor/seekh-kebab"
mkdir -p "$BASE_DIR/food/indian/tandoor/paneer-tikka"
mkdir -p "$BASE_DIR/food/international/chinese/noodles-hakka"
mkdir -p "$BASE_DIR/food/international/chinese/fried-rice"
mkdir -p "$BASE_DIR/food/international/chinese/manchurian"
mkdir -p "$BASE_DIR/food/international/italian/pizza-margherita"
mkdir -p "$BASE_DIR/food/international/italian/pasta-alfredo"
mkdir -p "$BASE_DIR/food/international/italian/lasagna"
mkdir -p "$BASE_DIR/food/international/american/burger-chicken"
mkdir -p "$BASE_DIR/food/international/american/burger-veg"
mkdir -p "$BASE_DIR/food/international/american/hot-dog"
mkdir -p "$BASE_DIR/food/international/american/sandwich-club"

# Sweets & Desserts (40 products)
mkdir -p "$BASE_DIR/food/sweets/traditional/gulab-jamun"
mkdir -p "$BASE_DIR/food/sweets/traditional/rasgulla"
mkdir -p "$BASE_DIR/food/sweets/traditional/rasmalai"
mkdir -p "$BASE_DIR/food/sweets/traditional/kaju-katli"
mkdir -p "$BASE_DIR/food/sweets/traditional/soan-papdi"
mkdir -p "$BASE_DIR/food/sweets/traditional/ladoo-motichoor"
mkdir -p "$BASE_DIR/food/sweets/traditional/ladoo-besan"
mkdir -p "$BASE_DIR/food/sweets/traditional/barfi-milk"
mkdir -p "$BASE_DIR/food/sweets/traditional/barfi-coconut"
mkdir -p "$BASE_DIR/food/sweets/traditional/halwa-gajar"
mkdir -p "$BASE_DIR/food/sweets/traditional/halwa-moong"
mkdir -p "$BASE_DIR/food/sweets/traditional/jalebi"
mkdir -p "$BASE_DIR/food/sweets/traditional/imarti"
mkdir -p "$BASE_DIR/food/sweets/traditional/rabri"
mkdir -p "$BASE_DIR/food/sweets/traditional/kheer"
mkdir -p "$BASE_DIR/food/sweets/bengali/sandesh"
mkdir -p "$BASE_DIR/food/sweets/bengali/mishti-doi"
mkdir -p "$BASE_DIR/food/sweets/bengali/chom-chom"
mkdir -p "$BASE_DIR/food/sweets/bengali/kalakand"
mkdir -p "$BASE_DIR/food/sweets/bengali/ras-malai"
mkdir -p "$BASE_DIR/food/desserts/ice-cream/vanilla"
mkdir -p "$BASE_DIR/food/desserts/ice-cream/chocolate"
mkdir -p "$BASE_DIR/food/desserts/ice-cream/strawberry"
mkdir -p "$BASE_DIR/food/desserts/ice-cream/butterscotch"
mkdir -p "$BASE_DIR/food/desserts/ice-cream/kulfi-malai"
mkdir -p "$BASE_DIR/food/desserts/cakes/chocolate-cake"
mkdir -p "$BASE_DIR/food/desserts/cakes/black-forest"
mkdir -p "$BASE_DIR/food/desserts/cakes/red-velvet"
mkdir -p "$BASE_DIR/food/desserts/cakes/pineapple-cake"
mkdir -p "$BASE_DIR/food/desserts/cakes/butterscotch-cake"
mkdir -p "$BASE_DIR/food/desserts/pastries/chocolate-pastry"
mkdir -p "$BASE_DIR/food/desserts/pastries/strawberry-pastry"
mkdir -p "$BASE_DIR/food/desserts/pastries/blueberry-cheesecake"
mkdir -p "$BASE_DIR/food/desserts/western/brownie-walnut"
mkdir -p "$BASE_DIR/food/desserts/western/donut-glazed"
mkdir -p "$BASE_DIR/food/desserts/western/macaron"
mkdir -p "$BASE_DIR/food/desserts/western/tiramisu"
mkdir -p "$BASE_DIR/food/desserts/western/mousse-chocolate"
mkdir -p "$BASE_DIR/food/desserts/western/pudding-caramel"
mkdir -p "$BASE_DIR/food/desserts/western/pancake"

# Bakery Products (35 products)
mkdir -p "$BASE_DIR/food/bakery/breads/white-bread"
mkdir -p "$BASE_DIR/food/bakery/breads/brown-bread"
mkdir -p "$BASE_DIR/food/bakery/breads/multigrain-bread"
mkdir -p "$BASE_DIR/food/bakery/breads/garlic-bread"
mkdir -p "$BASE_DIR/food/bakery/breads/baguette"
mkdir -p "$BASE_DIR/food/bakery/breads/pita-bread"
mkdir -p "$BASE_DIR/food/bakery/buns/burger-bun"
mkdir -p "$BASE_DIR/food/bakery/buns/pav-bun"
mkdir -p "$BASE_DIR/food/bakery/buns/hot-dog-bun"
mkdir -p "$BASE_DIR/food/bakery/croissant/plain-croissant"
mkdir -p "$BASE_DIR/food/bakery/croissant/chocolate-croissant"
mkdir -p "$BASE_DIR/food/bakery/croissant/almond-croissant"
mkdir -p "$BASE_DIR/food/bakery/indian-breads/naan-plain"
mkdir -p "$BASE_DIR/food/bakery/indian-breads/naan-butter"
mkdir -p "$BASE_DIR/food/bakery/indian-breads/naan-garlic"
mkdir -p "$BASE_DIR/food/bakery/indian-breads/kulcha"
mkdir -p "$BASE_DIR/food/bakery/indian-breads/roti-tandoori"
mkdir -p "$BASE_DIR/food/bakery/indian-breads/paratha"
mkdir -p "$BASE_DIR/food/bakery/cookies/butter-cookies"
mkdir -p "$BASE_DIR/food/bakery/cookies/chocolate-chip"
mkdir -p "$BASE_DIR/food/bakery/cookies/oatmeal-cookies"
mkdir -p "$BASE_DIR/food/bakery/cookies/almond-cookies"
mkdir -p "$BASE_DIR/food/bakery/biscuits/marie-biscuit"
mkdir -p "$BASE_DIR/food/bakery/biscuits/cream-biscuit"
mkdir -p "$BASE_DIR/food/bakery/biscuits/digestive-biscuit"
mkdir -p "$BASE_DIR/food/bakery/snacks/puff-veg"
mkdir -p "$BASE_DIR/food/bakery/snacks/puff-chicken"
mkdir -p "$BASE_DIR/food/bakery/snacks/samosa-mini"
mkdir -p "$BASE_DIR/food/bakery/snacks/kachori-mini"
mkdir -p "$BASE_DIR/food/bakery/muffins/blueberry-muffin"
mkdir -p "$BASE_DIR/food/bakery/muffins/chocolate-muffin"
mkdir -p "$BASE_DIR/food/bakery/muffins/banana-muffin"
mkdir -p "$BASE_DIR/food/bakery/others/rusk"
mkdir -p "$BASE_DIR/food/bakery/others/breadstick"
mkdir -p "$BASE_DIR/food/bakery/others/pizza-base"

# Beverages (35 products)
mkdir -p "$BASE_DIR/food/beverages/tea/masala-chai"
mkdir -p "$BASE_DIR/food/beverages/tea/green-tea"
mkdir -p "$BASE_DIR/food/beverages/tea/black-tea"
mkdir -p "$BASE_DIR/food/beverages/tea/lemon-tea"
mkdir -p "$BASE_DIR/food/beverages/tea/iced-tea"
mkdir -p "$BASE_DIR/food/beverages/coffee/espresso"
mkdir -p "$BASE_DIR/food/beverages/coffee/cappuccino"
mkdir -p "$BASE_DIR/food/beverages/coffee/latte"
mkdir -p "$BASE_DIR/food/beverages/coffee/americano"
mkdir -p "$BASE_DIR/food/beverages/coffee/cold-coffee"
mkdir -p "$BASE_DIR/food/beverages/coffee/filter-coffee"
mkdir -p "$BASE_DIR/food/beverages/juices/orange-juice"
mkdir -p "$BASE_DIR/food/beverages/juices/apple-juice"
mkdir -p "$BASE_DIR/food/beverages/juices/mango-juice"
mkdir -p "$BASE_DIR/food/beverages/juices/mixed-fruit"
mkdir -p "$BASE_DIR/food/beverages/juices/sugarcane-juice"
mkdir -p "$BASE_DIR/food/beverages/shakes/chocolate-shake"
mkdir -p "$BASE_DIR/food/beverages/shakes/vanilla-shake"
mkdir -p "$BASE_DIR/food/beverages/shakes/strawberry-shake"
mkdir -p "$BASE_DIR/food/beverages/shakes/mango-shake"
mkdir -p "$BASE_DIR/food/beverages/shakes/banana-shake"
mkdir -p "$BASE_DIR/food/beverages/traditional/lassi-sweet"
mkdir -p "$BASE_DIR/food/beverages/traditional/lassi-mango"
mkdir -p "$BASE_DIR/food/beverages/traditional/buttermilk"
mkdir -p "$BASE_DIR/food/beverages/traditional/coconut-water"
mkdir -p "$BASE_DIR/food/beverages/traditional/jaljeera"
mkdir -p "$BASE_DIR/food/beverages/sodas/cola"
mkdir -p "$BASE_DIR/food/beverages/sodas/lemon-soda"
mkdir -p "$BASE_DIR/food/beverages/sodas/orange-soda"
mkdir -p "$BASE_DIR/food/beverages/mocktails/virgin-mojito"
mkdir -p "$BASE_DIR/food/beverages/mocktails/blue-lagoon"
mkdir -p "$BASE_DIR/food/beverages/energy/energy-drink"
mkdir -p "$BASE_DIR/food/beverages/energy/sports-drink"
mkdir -p "$BASE_DIR/food/beverages/water/mineral-water"
mkdir -p "$BASE_DIR/food/beverages/water/packaged-water"

# GROCERY & STAPLES (100 products)
echo "Creating Grocery folders..."

# Rice & Grains (20 products)
mkdir -p "$BASE_DIR/grocery/rice/basmati/basmati-premium"
mkdir -p "$BASE_DIR/grocery/rice/basmati/basmati-regular"
mkdir -p "$BASE_DIR/grocery/rice/regular/sona-masoori"
mkdir -p "$BASE_DIR/grocery/rice/regular/ponni-rice"
mkdir -p "$BASE_DIR/grocery/rice/regular/kolam-rice"
mkdir -p "$BASE_DIR/grocery/rice/special/brown-rice"
mkdir -p "$BASE_DIR/grocery/rice/special/red-rice"
mkdir -p "$BASE_DIR/grocery/rice/special/black-rice"
mkdir -p "$BASE_DIR/grocery/flour/wheat/wheat-flour-regular"
mkdir -p "$BASE_DIR/grocery/flour/wheat/wheat-flour-multigrain"
mkdir -p "$BASE_DIR/grocery/flour/wheat/whole-wheat-atta"
mkdir -p "$BASE_DIR/grocery/flour/other/besan-flour"
mkdir -p "$BASE_DIR/grocery/flour/other/maida-flour"
mkdir -p "$BASE_DIR/grocery/flour/other/rice-flour"
mkdir -p "$BASE_DIR/grocery/flour/other/ragi-flour"
mkdir -p "$BASE_DIR/grocery/flour/other/corn-flour"
mkdir -p "$BASE_DIR/grocery/grains/semolina-rava"
mkdir -p "$BASE_DIR/grocery/grains/broken-wheat"
mkdir -p "$BASE_DIR/grocery/grains/quinoa"
mkdir -p "$BASE_DIR/grocery/grains/oats"

# Pulses & Lentils (15 products)
mkdir -p "$BASE_DIR/grocery/pulses/dal/toor-dal"
mkdir -p "$BASE_DIR/grocery/pulses/dal/moong-dal"
mkdir -p "$BASE_DIR/grocery/pulses/dal/masoor-dal"
mkdir -p "$BASE_DIR/grocery/pulses/dal/chana-dal"
mkdir -p "$BASE_DIR/grocery/pulses/dal/urad-dal"
mkdir -p "$BASE_DIR/grocery/pulses/beans/rajma-kidney"
mkdir -p "$BASE_DIR/grocery/pulses/beans/chana-kabuli"
mkdir -p "$BASE_DIR/grocery/pulses/beans/chana-kala"
mkdir -p "$BASE_DIR/grocery/pulses/beans/lobia"
mkdir -p "$BASE_DIR/grocery/pulses/beans/soybean"
mkdir -p "$BASE_DIR/grocery/pulses/peas/green-peas"
mkdir -p "$BASE_DIR/grocery/pulses/peas/white-peas"
mkdir -p "$BASE_DIR/grocery/pulses/others/peanuts"
mkdir -p "$BASE_DIR/grocery/pulses/others/horse-gram"
mkdir -p "$BASE_DIR/grocery/pulses/others/moth-beans"

# Oils & Ghee (10 products)
mkdir -p "$BASE_DIR/grocery/oils/cooking/sunflower-oil"
mkdir -p "$BASE_DIR/grocery/oils/cooking/mustard-oil"
mkdir -p "$BASE_DIR/grocery/oils/cooking/coconut-oil"
mkdir -p "$BASE_DIR/grocery/oils/cooking/groundnut-oil"
mkdir -p "$BASE_DIR/grocery/oils/cooking/rice-bran-oil"
mkdir -p "$BASE_DIR/grocery/oils/cooking/soybean-oil"
mkdir -p "$BASE_DIR/grocery/oils/special/olive-oil"
mkdir -p "$BASE_DIR/grocery/oils/special/sesame-oil"
mkdir -p "$BASE_DIR/grocery/oils/ghee/cow-ghee"
mkdir -p "$BASE_DIR/grocery/oils/ghee/buffalo-ghee"

# Spices & Masalas (15 products)
mkdir -p "$BASE_DIR/grocery/spices/whole/cumin-seeds"
mkdir -p "$BASE_DIR/grocery/spices/whole/coriander-seeds"
mkdir -p "$BASE_DIR/grocery/spices/whole/mustard-seeds"
mkdir -p "$BASE_DIR/grocery/spices/whole/fenugreek-seeds"
mkdir -p "$BASE_DIR/grocery/spices/whole/black-pepper"
mkdir -p "$BASE_DIR/grocery/spices/powder/turmeric-powder"
mkdir -p "$BASE_DIR/grocery/spices/powder/red-chilli-powder"
mkdir -p "$BASE_DIR/grocery/spices/powder/coriander-powder"
mkdir -p "$BASE_DIR/grocery/spices/powder/garam-masala"
mkdir -p "$BASE_DIR/grocery/spices/powder/sambar-powder"
mkdir -p "$BASE_DIR/grocery/spices/special/saffron"
mkdir -p "$BASE_DIR/grocery/spices/special/cardamom"
mkdir -p "$BASE_DIR/grocery/spices/special/cinnamon"
mkdir -p "$BASE_DIR/grocery/spices/special/cloves"
mkdir -p "$BASE_DIR/grocery/spices/special/nutmeg"

# Dairy Products (15 products)
mkdir -p "$BASE_DIR/grocery/dairy/milk/full-cream-milk"
mkdir -p "$BASE_DIR/grocery/dairy/milk/toned-milk"
mkdir -p "$BASE_DIR/grocery/dairy/milk/skimmed-milk"
mkdir -p "$BASE_DIR/grocery/dairy/milk/flavored-milk"
mkdir -p "$BASE_DIR/grocery/dairy/curd/plain-curd"
mkdir -p "$BASE_DIR/grocery/dairy/curd/greek-yogurt"
mkdir -p "$BASE_DIR/grocery/dairy/cheese/cheese-cubes"
mkdir -p "$BASE_DIR/grocery/dairy/cheese/cheese-slices"
mkdir -p "$BASE_DIR/grocery/dairy/cheese/mozzarella"
mkdir -p "$BASE_DIR/grocery/dairy/cheese/paneer"
mkdir -p "$BASE_DIR/grocery/dairy/butter/salted-butter"
mkdir -p "$BASE_DIR/grocery/dairy/butter/unsalted-butter"
mkdir -p "$BASE_DIR/grocery/dairy/others/cream"
mkdir -p "$BASE_DIR/grocery/dairy/others/condensed-milk"
mkdir -p "$BASE_DIR/grocery/dairy/others/milk-powder"

# Snacks & Dry Fruits (15 products)
mkdir -p "$BASE_DIR/grocery/snacks/chips/potato-chips"
mkdir -p "$BASE_DIR/grocery/snacks/chips/banana-chips"
mkdir -p "$BASE_DIR/grocery/snacks/namkeen/mixture"
mkdir -p "$BASE_DIR/grocery/snacks/namkeen/bhujia"
mkdir -p "$BASE_DIR/grocery/snacks/namkeen/chakli"
mkdir -p "$BASE_DIR/grocery/dry-fruits/nuts/almonds"
mkdir -p "$BASE_DIR/grocery/dry-fruits/nuts/cashews"
mkdir -p "$BASE_DIR/grocery/dry-fruits/nuts/walnuts"
mkdir -p "$BASE_DIR/grocery/dry-fruits/nuts/pistachios"
mkdir -p "$BASE_DIR/grocery/dry-fruits/dried/raisins"
mkdir -p "$BASE_DIR/grocery/dry-fruits/dried/dates"
mkdir -p "$BASE_DIR/grocery/dry-fruits/dried/figs"
mkdir -p "$BASE_DIR/grocery/dry-fruits/dried/apricots"
mkdir -p "$BASE_DIR/grocery/dry-fruits/seeds/flax-seeds"
mkdir -p "$BASE_DIR/grocery/dry-fruits/seeds/chia-seeds"

# Fruits & Vegetables (10 products)
mkdir -p "$BASE_DIR/grocery/fruits/seasonal/mango-alphonso"
mkdir -p "$BASE_DIR/grocery/fruits/seasonal/apple-kashmiri"
mkdir -p "$BASE_DIR/grocery/fruits/regular/banana"
mkdir -p "$BASE_DIR/grocery/fruits/regular/orange"
mkdir -p "$BASE_DIR/grocery/fruits/exotic/avocado"
mkdir -p "$BASE_DIR/grocery/vegetables/regular/tomato"
mkdir -p "$BASE_DIR/grocery/vegetables/regular/potato"
mkdir -p "$BASE_DIR/grocery/vegetables/regular/onion"
mkdir -p "$BASE_DIR/grocery/vegetables/leafy/spinach"
mkdir -p "$BASE_DIR/grocery/vegetables/leafy/coriander"

# BEAUTY & PERSONAL CARE (100 products)
echo "Creating Beauty folders..."

# Makeup (25 products)
mkdir -p "$BASE_DIR/beauty/makeup/face/foundation-liquid"
mkdir -p "$BASE_DIR/beauty/makeup/face/compact-powder"
mkdir -p "$BASE_DIR/beauty/makeup/face/concealer"
mkdir -p "$BASE_DIR/beauty/makeup/face/primer"
mkdir -p "$BASE_DIR/beauty/makeup/face/bb-cream"
mkdir -p "$BASE_DIR/beauty/makeup/face/blush"
mkdir -p "$BASE_DIR/beauty/makeup/face/highlighter"
mkdir -p "$BASE_DIR/beauty/makeup/lips/lipstick-red"
mkdir -p "$BASE_DIR/beauty/makeup/lips/lipstick-nude"
mkdir -p "$BASE_DIR/beauty/makeup/lips/lipgloss"
mkdir -p "$BASE_DIR/beauty/makeup/lips/lip-liner"
mkdir -p "$BASE_DIR/beauty/makeup/lips/lip-balm"
mkdir -p "$BASE_DIR/beauty/makeup/eyes/mascara"
mkdir -p "$BASE_DIR/beauty/makeup/eyes/eyeliner-liquid"
mkdir -p "$BASE_DIR/beauty/makeup/eyes/kajal"
mkdir -p "$BASE_DIR/beauty/makeup/eyes/eyeshadow-palette"
mkdir -p "$BASE_DIR/beauty/makeup/eyes/eyebrow-pencil"
mkdir -p "$BASE_DIR/beauty/makeup/nails/nail-polish-red"
mkdir -p "$BASE_DIR/beauty/makeup/nails/nail-polish-nude"
mkdir -p "$BASE_DIR/beauty/makeup/nails/nail-art-kit"
mkdir -p "$BASE_DIR/beauty/makeup/tools/makeup-brushes"
mkdir -p "$BASE_DIR/beauty/makeup/tools/beauty-blender"
mkdir -p "$BASE_DIR/beauty/makeup/remover/makeup-remover"
mkdir -p "$BASE_DIR/beauty/makeup/remover/micellar-water"
mkdir -p "$BASE_DIR/beauty/makeup/kits/bridal-kit"

# Skincare (25 products)
mkdir -p "$BASE_DIR/beauty/skincare/cleansers/face-wash-gel"
mkdir -p "$BASE_DIR/beauty/skincare/cleansers/face-wash-foam"
mkdir -p "$BASE_DIR/beauty/skincare/cleansers/cleansing-milk"
mkdir -p "$BASE_DIR/beauty/skincare/moisturizers/day-cream"
mkdir -p "$BASE_DIR/beauty/skincare/moisturizers/night-cream"
mkdir -p "$BASE_DIR/beauty/skincare/moisturizers/gel-moisturizer"
mkdir -p "$BASE_DIR/beauty/skincare/sun-protection/sunscreen-spf50"
mkdir -p "$BASE_DIR/beauty/skincare/sun-protection/sunscreen-spray"
mkdir -p "$BASE_DIR/beauty/skincare/treatments/serum-vitamin-c"
mkdir -p "$BASE_DIR/beauty/skincare/treatments/serum-hyaluronic"
mkdir -p "$BASE_DIR/beauty/skincare/treatments/face-oil"
mkdir -p "$BASE_DIR/beauty/skincare/masks/sheet-mask"
mkdir -p "$BASE_DIR/beauty/skincare/masks/clay-mask"
mkdir -p "$BASE_DIR/beauty/skincare/masks/peel-off-mask"
mkdir -p "$BASE_DIR/beauty/skincare/scrubs/face-scrub-walnut"
mkdir -p "$BASE_DIR/beauty/skincare/scrubs/face-scrub-coffee"
mkdir -p "$BASE_DIR/beauty/skincare/toners/toner-alcohol-free"
mkdir -p "$BASE_DIR/beauty/skincare/toners/rose-water"
mkdir -p "$BASE_DIR/beauty/skincare/eye-care/eye-cream"
mkdir -p "$BASE_DIR/beauty/skincare/eye-care/under-eye-patches"
mkdir -p "$BASE_DIR/beauty/skincare/acne/acne-gel"
mkdir -p "$BASE_DIR/beauty/skincare/acne/spot-treatment"
mkdir -p "$BASE_DIR/beauty/skincare/tools/face-roller"
mkdir -p "$BASE_DIR/beauty/skincare/tools/blackhead-remover"
mkdir -p "$BASE_DIR/beauty/skincare/kits/facial-kit"

# Hair Care (25 products)
mkdir -p "$BASE_DIR/beauty/haircare/shampoo/anti-dandruff"
mkdir -p "$BASE_DIR/beauty/haircare/shampoo/mild-shampoo"
mkdir -p "$BASE_DIR/beauty/haircare/shampoo/herbal-shampoo"
mkdir -p "$BASE_DIR/beauty/haircare/shampoo/dry-shampoo"
mkdir -p "$BASE_DIR/beauty/haircare/conditioner/smooth-conditioner"
mkdir -p "$BASE_DIR/beauty/haircare/conditioner/repair-conditioner"
mkdir -p "$BASE_DIR/beauty/haircare/oils/coconut-oil"
mkdir -p "$BASE_DIR/beauty/haircare/oils/almond-oil"
mkdir -p "$BASE_DIR/beauty/haircare/oils/argan-oil"
mkdir -p "$BASE_DIR/beauty/haircare/treatments/hair-serum"
mkdir -p "$BASE_DIR/beauty/haircare/treatments/hair-mask"
mkdir -p "$BASE_DIR/beauty/haircare/treatments/hair-spa"
mkdir -p "$BASE_DIR/beauty/haircare/styling/hair-gel"
mkdir -p "$BASE_DIR/beauty/haircare/styling/hair-wax"
mkdir -p "$BASE_DIR/beauty/haircare/styling/hair-spray"
mkdir -p "$BASE_DIR/beauty/haircare/coloring/hair-color-black"
mkdir -p "$BASE_DIR/beauty/haircare/coloring/hair-color-brown"
mkdir -p "$BASE_DIR/beauty/haircare/coloring/henna"
mkdir -p "$BASE_DIR/beauty/haircare/tools/hair-straightener"
mkdir -p "$BASE_DIR/beauty/haircare/tools/hair-curler"
mkdir -p "$BASE_DIR/beauty/haircare/tools/hair-dryer"
mkdir -p "$BASE_DIR/beauty/haircare/tools/hair-trimmer"
mkdir -p "$BASE_DIR/beauty/haircare/accessories/hair-brush"
mkdir -p "$BASE_DIR/beauty/haircare/accessories/hair-comb"
mkdir -p "$BASE_DIR/beauty/haircare/accessories/hair-bands"

# Bath & Body (25 products)
mkdir -p "$BASE_DIR/beauty/bath/soaps/bathing-soap"
mkdir -p "$BASE_DIR/beauty/bath/soaps/handmade-soap"
mkdir -p "$BASE_DIR/beauty/bath/shower/shower-gel"
mkdir -p "$BASE_DIR/beauty/bath/shower/body-wash"
mkdir -p "$BASE_DIR/beauty/body/lotions/body-lotion"
mkdir -p "$BASE_DIR/beauty/body/lotions/body-butter"
mkdir -p "$BASE_DIR/beauty/body/scrubs/body-scrub"
mkdir -p "$BASE_DIR/beauty/body/scrubs/foot-scrub"
mkdir -p "$BASE_DIR/beauty/fragrances/perfumes/perfume-men"
mkdir -p "$BASE_DIR/beauty/fragrances/perfumes/perfume-women"
mkdir -p "$BASE_DIR/beauty/fragrances/deodorants/deo-men"
mkdir -p "$BASE_DIR/beauty/fragrances/deodorants/deo-women"
mkdir -p "$BASE_DIR/beauty/fragrances/mists/body-mist"
mkdir -p "$BASE_DIR/beauty/fragrances/attars/attar-rose"
mkdir -p "$BASE_DIR/beauty/mens-grooming/shaving/shaving-cream"
mkdir -p "$BASE_DIR/beauty/mens-grooming/shaving/after-shave"
mkdir -p "$BASE_DIR/beauty/mens-grooming/shaving/razor"
mkdir -p "$BASE_DIR/beauty/mens-grooming/beard/beard-oil"
mkdir -p "$BASE_DIR/beauty/mens-grooming/beard/beard-wax"
mkdir -p "$BASE_DIR/beauty/personal-hygiene/oral/toothpaste"
mkdir -p "$BASE_DIR/beauty/personal-hygiene/oral/mouthwash"
mkdir -p "$BASE_DIR/beauty/personal-hygiene/feminine/sanitary-pads"
mkdir -p "$BASE_DIR/beauty/personal-hygiene/others/hand-sanitizer"
mkdir -p "$BASE_DIR/beauty/personal-hygiene/others/talcum-powder"

# HOME & FURNITURE (100 products)
echo "Creating Home & Furniture folders..."

# Living Room Furniture (20 products)
mkdir -p "$BASE_DIR/home/living-room/sofas/3-seater-sofa"
mkdir -p "$BASE_DIR/home/living-room/sofas/l-shaped-sofa"
mkdir -p "$BASE_DIR/home/living-room/sofas/sofa-bed"
mkdir -p "$BASE_DIR/home/living-room/sofas/recliner-sofa"
mkdir -p "$BASE_DIR/home/living-room/tables/coffee-table-wooden"
mkdir -p "$BASE_DIR/home/living-room/tables/coffee-table-glass"
mkdir -p "$BASE_DIR/home/living-room/tables/center-table"
mkdir -p "$BASE_DIR/home/living-room/tables/side-table"
mkdir -p "$BASE_DIR/home/living-room/tv-units/tv-stand-modern"
mkdir -p "$BASE_DIR/home/living-room/tv-units/tv-cabinet"
mkdir -p "$BASE_DIR/home/living-room/tv-units/wall-mounted-tv-unit"
mkdir -p "$BASE_DIR/home/living-room/seating/ottoman"
mkdir -p "$BASE_DIR/home/living-room/seating/bean-bag"
mkdir -p "$BASE_DIR/home/living-room/seating/accent-chair"
mkdir -p "$BASE_DIR/home/living-room/storage/bookshelf"
mkdir -p "$BASE_DIR/home/living-room/storage/display-cabinet"
mkdir -p "$BASE_DIR/home/living-room/storage/shoe-rack"
mkdir -p "$BASE_DIR/home/living-room/decor/wall-clock"
mkdir -p "$BASE_DIR/home/living-room/decor/wall-painting"
mkdir -p "$BASE_DIR/home/living-room/decor/floor-lamp"

# Bedroom Furniture (20 products)
mkdir -p "$BASE_DIR/home/bedroom/beds/double-bed-wooden"
mkdir -p "$BASE_DIR/home/bedroom/beds/single-bed"
mkdir -p "$BASE_DIR/home/bedroom/beds/bunk-bed"
mkdir -p "$BASE_DIR/home/bedroom/beds/storage-bed"
mkdir -p "$BASE_DIR/home/bedroom/mattresses/foam-mattress"
mkdir -p "$BASE_DIR/home/bedroom/mattresses/spring-mattress"
mkdir -p "$BASE_DIR/home/bedroom/mattresses/coir-mattress"
mkdir -p "$BASE_DIR/home/bedroom/mattresses/ortho-mattress"
mkdir -p "$BASE_DIR/home/bedroom/wardrobes/3-door-wardrobe"
mkdir -p "$BASE_DIR/home/bedroom/wardrobes/sliding-wardrobe"
mkdir -p "$BASE_DIR/home/bedroom/wardrobes/2-door-wardrobe"
mkdir -p "$BASE_DIR/home/bedroom/storage/dresser-mirror"
mkdir -p "$BASE_DIR/home/bedroom/storage/chest-drawers"
mkdir -p "$BASE_DIR/home/bedroom/storage/bedside-table"
mkdir -p "$BASE_DIR/home/bedroom/bedding/bedsheet-double"
mkdir -p "$BASE_DIR/home/bedroom/bedding/bedsheet-single"
mkdir -p "$BASE_DIR/home/bedroom/bedding/blanket"
mkdir -p "$BASE_DIR/home/bedroom/bedding/comforter"
mkdir -p "$BASE_DIR/home/bedroom/bedding/pillow"
mkdir -p "$BASE_DIR/home/bedroom/bedding/cushion"

# Kitchen & Dining (30 products)
mkdir -p "$BASE_DIR/home/kitchen/tables/dining-table-6-seater"
mkdir -p "$BASE_DIR/home/kitchen/tables/dining-table-4-seater"
mkdir -p "$BASE_DIR/home/kitchen/chairs/dining-chairs"
mkdir -p "$BASE_DIR/home/kitchen/chairs/bar-stools"
mkdir -p "$BASE_DIR/home/kitchen/storage/kitchen-cabinet"
mkdir -p "$BASE_DIR/home/kitchen/storage/pantry-unit"
mkdir -p "$BASE_DIR/home/kitchen/cookware/pressure-cooker"
mkdir -p "$BASE_DIR/home/kitchen/cookware/kadai-nonstick"
mkdir -p "$BASE_DIR/home/kitchen/cookware/tawa-nonstick"
mkdir -p "$BASE_DIR/home/kitchen/cookware/sauce-pan"
mkdir -p "$BASE_DIR/home/kitchen/dinnerware/dinner-set"
mkdir -p "$BASE_DIR/home/kitchen/dinnerware/plate-set"
mkdir -p "$BASE_DIR/home/kitchen/dinnerware/bowl-set"
mkdir -p "$BASE_DIR/home/kitchen/dinnerware/cup-saucer"
mkdir -p "$BASE_DIR/home/kitchen/glassware/glass-set"
mkdir -p "$BASE_DIR/home/kitchen/glassware/mug-set"
mkdir -p "$BASE_DIR/home/kitchen/cutlery/cutlery-set"
mkdir -p "$BASE_DIR/home/kitchen/cutlery/knife-set"
mkdir -p "$BASE_DIR/home/kitchen/storage-containers/container-set"
mkdir -p "$BASE_DIR/home/kitchen/storage-containers/jar-set"
mkdir -p "$BASE_DIR/home/kitchen/bottles/water-bottle-steel"
mkdir -p "$BASE_DIR/home/kitchen/bottles/flask"
mkdir -p "$BASE_DIR/home/kitchen/lunch-boxes/lunch-box-steel"
mkdir -p "$BASE_DIR/home/kitchen/lunch-boxes/tiffin-box"
mkdir -p "$BASE_DIR/home/kitchen/tools/chopping-board"
mkdir -p "$BASE_DIR/home/kitchen/tools/grater"
mkdir -p "$BASE_DIR/home/kitchen/tools/peeler"
mkdir -p "$BASE_DIR/home/kitchen/tools/strainer"
mkdir -p "$BASE_DIR/home/kitchen/linen/kitchen-towel"
mkdir -p "$BASE_DIR/home/kitchen/linen/table-cloth"

# Home Decor (30 products)
mkdir -p "$BASE_DIR/home/decor/wall/painting-abstract"
mkdir -p "$BASE_DIR/home/decor/wall/painting-landscape"
mkdir -p "$BASE_DIR/home/decor/wall/photo-frame"
mkdir -p "$BASE_DIR/home/decor/wall/wall-mirror"
mkdir -p "$BASE_DIR/home/decor/wall/wall-sticker"
mkdir -p "$BASE_DIR/home/decor/wall/wallpaper"
mkdir -p "$BASE_DIR/home/decor/lighting/ceiling-light"
mkdir -p "$BASE_DIR/home/decor/lighting/chandelier"
mkdir -p "$BASE_DIR/home/decor/lighting/table-lamp"
mkdir -p "$BASE_DIR/home/decor/lighting/floor-lamp"
mkdir -p "$BASE_DIR/home/decor/curtains/window-curtain"
mkdir -p "$BASE_DIR/home/decor/curtains/door-curtain"
mkdir -p "$BASE_DIR/home/decor/curtains/blinds"
mkdir -p "$BASE_DIR/home/decor/rugs/carpet"
mkdir -p "$BASE_DIR/home/decor/rugs/door-mat"
mkdir -p "$BASE_DIR/home/decor/rugs/bathroom-mat"
mkdir -p "$BASE_DIR/home/decor/vases/ceramic-vase"
mkdir -p "$BASE_DIR/home/decor/vases/glass-vase"
mkdir -p "$BASE_DIR/home/decor/plants/artificial-plant"
mkdir -p "$BASE_DIR/home/decor/plants/planter"
mkdir -p "$BASE_DIR/home/decor/showpieces/buddha-statue"
mkdir -p "$BASE_DIR/home/decor/showpieces/elephant-figurine"
mkdir -p "$BASE_DIR/home/decor/showpieces/wind-chimes"
mkdir -p "$BASE_DIR/home/decor/candles/scented-candle"
mkdir -p "$BASE_DIR/home/decor/candles/candle-holder"
mkdir -p "$BASE_DIR/home/decor/aromatherapy/incense-sticks"
mkdir -p "$BASE_DIR/home/decor/aromatherapy/diffuser"
mkdir -p "$BASE_DIR/home/decor/festive/diwali-lights"
mkdir -p "$BASE_DIR/home/decor/festive/christmas-decor"
mkdir -p "$BASE_DIR/home/decor/festive/rangoli-stickers"

# SPORTS, HEALTH & OTHERS (150 products)
echo "Creating remaining category folders..."

# Sports & Fitness (30 products)
mkdir -p "$BASE_DIR/sports/cricket/bat/cricket-bat-english-willow"
mkdir -p "$BASE_DIR/sports/cricket/bat/cricket-bat-kashmir"
mkdir -p "$BASE_DIR/sports/cricket/ball/cricket-ball-leather"
mkdir -p "$BASE_DIR/sports/cricket/protective/cricket-gloves"
mkdir -p "$BASE_DIR/sports/cricket/protective/cricket-helmet"
mkdir -p "$BASE_DIR/sports/cricket/protective/cricket-pads"
mkdir -p "$BASE_DIR/sports/football/ball/football-size5"
mkdir -p "$BASE_DIR/sports/football/shoes/football-studs"
mkdir -p "$BASE_DIR/sports/football/protective/shin-guards"
mkdir -p "$BASE_DIR/sports/badminton/racket/yonex-racket"
mkdir -p "$BASE_DIR/sports/badminton/racket/li-ning-racket"
mkdir -p "$BASE_DIR/sports/badminton/shuttlecock/feather-shuttle"
mkdir -p "$BASE_DIR/sports/tennis/racket/tennis-racket"
mkdir -p "$BASE_DIR/sports/tennis/ball/tennis-ball"
mkdir -p "$BASE_DIR/sports/basketball/ball/basketball"
mkdir -p "$BASE_DIR/sports/basketball/shoes/basketball-shoes"
mkdir -p "$BASE_DIR/sports/fitness/yoga/yoga-mat"
mkdir -p "$BASE_DIR/sports/fitness/yoga/yoga-block"
mkdir -p "$BASE_DIR/sports/fitness/weights/dumbbell-set"
mkdir -p "$BASE_DIR/sports/fitness/weights/kettlebell"
mkdir -p "$BASE_DIR/sports/fitness/cardio/skipping-rope"
mkdir -p "$BASE_DIR/sports/fitness/cardio/resistance-band"
mkdir -p "$BASE_DIR/sports/fitness/equipment/treadmill"
mkdir -p "$BASE_DIR/sports/fitness/equipment/exercise-bike"
mkdir -p "$BASE_DIR/sports/nutrition/protein/whey-protein"
mkdir -p "$BASE_DIR/sports/nutrition/supplements/bcaa"
mkdir -p "$BASE_DIR/sports/nutrition/supplements/creatine"
mkdir -p "$BASE_DIR/sports/accessories/gym-bag"
mkdir -p "$BASE_DIR/sports/accessories/water-bottle"
mkdir -p "$BASE_DIR/sports/accessories/gym-gloves"

# Health & Medical (30 products)
mkdir -p "$BASE_DIR/health/medicines/pain-relief/paracetamol"
mkdir -p "$BASE_DIR/health/medicines/pain-relief/ibuprofen"
mkdir -p "$BASE_DIR/health/medicines/cold/cough-syrup"
mkdir -p "$BASE_DIR/health/medicines/digestive/antacid"
mkdir -p "$BASE_DIR/health/vitamins/vitamin-c"
mkdir -p "$BASE_DIR/health/vitamins/vitamin-d3"
mkdir -p "$BASE_DIR/health/vitamins/multivitamin"
mkdir -p "$BASE_DIR/health/supplements/calcium"
mkdir -p "$BASE_DIR/health/supplements/iron"
mkdir -p "$BASE_DIR/health/supplements/omega-3"
mkdir -p "$BASE_DIR/health/devices/thermometer/digital-thermometer"
mkdir -p "$BASE_DIR/health/devices/bp-monitor/bp-monitor-digital"
mkdir -p "$BASE_DIR/health/devices/glucometer/glucometer-kit"
mkdir -p "$BASE_DIR/health/devices/oximeter/pulse-oximeter"
mkdir -p "$BASE_DIR/health/devices/nebulizer/nebulizer-portable"
mkdir -p "$BASE_DIR/health/first-aid/bandaid/bandaid-pack"
mkdir -p "$BASE_DIR/health/first-aid/cotton/cotton-roll"
mkdir -p "$BASE_DIR/health/first-aid/antiseptic/dettol"
mkdir -p "$BASE_DIR/health/first-aid/kit/first-aid-kit"
mkdir -p "$BASE_DIR/health/personal/mask-n95"
mkdir -p "$BASE_DIR/health/personal/sanitizer"
mkdir -p "$BASE_DIR/health/personal/gloves"
mkdir -p "$BASE_DIR/health/ortho/knee-cap"
mkdir -p "$BASE_DIR/health/ortho/back-support"
mkdir -p "$BASE_DIR/health/ortho/ankle-support"
mkdir -p "$BASE_DIR/health/baby/diapers"
mkdir -p "$BASE_DIR/health/baby/baby-food"
mkdir -p "$BASE_DIR/health/baby/baby-lotion"
mkdir -p "$BASE_DIR/health/elderly/wheelchair"
mkdir -p "$BASE_DIR/health/elderly/walking-stick"

# Jewelry (30 products)
mkdir -p "$BASE_DIR/jewelry/gold/necklace/gold-necklace-traditional"
mkdir -p "$BASE_DIR/jewelry/gold/necklace/gold-chain"
mkdir -p "$BASE_DIR/jewelry/gold/earrings/gold-studs"
mkdir -p "$BASE_DIR/jewelry/gold/earrings/gold-jhumkas"
mkdir -p "$BASE_DIR/jewelry/gold/bangles/gold-bangles"
mkdir -p "$BASE_DIR/jewelry/gold/rings/gold-ring-plain"
mkdir -p "$BASE_DIR/jewelry/gold/rings/gold-ring-stone"
mkdir -p "$BASE_DIR/jewelry/gold/pendant/gold-pendant"
mkdir -p "$BASE_DIR/jewelry/diamond/rings/diamond-solitaire"
mkdir -p "$BASE_DIR/jewelry/diamond/earrings/diamond-studs"
mkdir -p "$BASE_DIR/jewelry/diamond/necklace/diamond-necklace"
mkdir -p "$BASE_DIR/jewelry/diamond/bracelet/diamond-bracelet"
mkdir -p "$BASE_DIR/jewelry/silver/anklets/silver-anklets"
mkdir -p "$BASE_DIR/jewelry/silver/rings/silver-ring"
mkdir -p "$BASE_DIR/jewelry/silver/earrings/silver-earrings"
mkdir -p "$BASE_DIR/jewelry/silver/bracelet/silver-bracelet"
mkdir -p "$BASE_DIR/jewelry/fashion/earrings/oxidized-earrings"
mkdir -p "$BASE_DIR/jewelry/fashion/necklace/fashion-necklace"
mkdir -p "$BASE_DIR/jewelry/fashion/bracelet/charm-bracelet"
mkdir -p "$BASE_DIR/jewelry/fashion/rings/fashion-rings"
mkdir -p "$BASE_DIR/jewelry/traditional/temple/temple-jewelry"
mkdir -p "$BASE_DIR/jewelry/traditional/kundan/kundan-set"
mkdir -p "$BASE_DIR/jewelry/traditional/pearl/pearl-necklace"
mkdir -p "$BASE_DIR/jewelry/watches/mens/titan-watch"
mkdir -p "$BASE_DIR/jewelry/watches/womens/sonata-watch"
mkdir -p "$BASE_DIR/jewelry/watches/smart/smart-watch"
mkdir -p "$BASE_DIR/jewelry/watches/luxury/tissot-watch"
mkdir -p "$BASE_DIR/jewelry/accessories/jewelry-box"
mkdir -p "$BASE_DIR/jewelry/accessories/brooch"
mkdir -p "$BASE_DIR/jewelry/accessories/nose-ring"

# Footwear (30 products)
mkdir -p "$BASE_DIR/footwear/mens/formal/oxford-shoes-black"
mkdir -p "$BASE_DIR/footwear/mens/formal/derby-shoes-brown"
mkdir -p "$BASE_DIR/footwear/mens/formal/loafers-leather"
mkdir -p "$BASE_DIR/footwear/mens/casual/sneakers-white"
mkdir -p "$BASE_DIR/footwear/mens/casual/canvas-shoes"
mkdir -p "$BASE_DIR/footwear/mens/casual/boat-shoes"
mkdir -p "$BASE_DIR/footwear/mens/sports/running-shoes"
mkdir -p "$BASE_DIR/footwear/mens/sports/training-shoes"
mkdir -p "$BASE_DIR/footwear/mens/sandals/leather-sandals"
mkdir -p "$BASE_DIR/footwear/mens/sandals/sports-sandals"
mkdir -p "$BASE_DIR/footwear/mens/ethnic/mojari"
mkdir -p "$BASE_DIR/footwear/mens/ethnic/kolhapuri"
mkdir -p "$BASE_DIR/footwear/womens/heels/stiletto-black"
mkdir -p "$BASE_DIR/footwear/womens/heels/block-heels"
mkdir -p "$BASE_DIR/footwear/womens/heels/wedges"
mkdir -p "$BASE_DIR/footwear/womens/flats/ballerinas"
mkdir -p "$BASE_DIR/footwear/womens/flats/pointed-flats"
mkdir -p "$BASE_DIR/footwear/womens/casual/sneakers-womens"
mkdir -p "$BASE_DIR/footwear/womens/sandals/flat-sandals"
mkdir -p "$BASE_DIR/footwear/womens/sandals/heeled-sandals"
mkdir -p "$BASE_DIR/footwear/womens/boots/ankle-boots"
mkdir -p "$BASE_DIR/footwear/womens/ethnic/juttis"
mkdir -p "$BASE_DIR/footwear/kids/school/school-shoes-black"
mkdir -p "$BASE_DIR/footwear/kids/casual/kids-sneakers"
mkdir -p "$BASE_DIR/footwear/kids/sandals/kids-sandals"
mkdir -p "$BASE_DIR/footwear/slippers/mens-slippers"
mkdir -p "$BASE_DIR/footwear/slippers/womens-slippers"
mkdir -p "$BASE_DIR/footwear/slippers/flip-flops"
mkdir -p "$BASE_DIR/footwear/accessories/shoe-polish"
mkdir -p "$BASE_DIR/footwear/accessories/insoles"

# Books & Stationery (30 products)
mkdir -p "$BASE_DIR/books/fiction/novels/bestseller-novel"
mkdir -p "$BASE_DIR/books/fiction/thriller/mystery-thriller"
mkdir -p "$BASE_DIR/books/fiction/romance/romance-novel"
mkdir -p "$BASE_DIR/books/non-fiction/self-help/motivation-book"
mkdir -p "$BASE_DIR/books/non-fiction/biography/autobiography"
mkdir -p "$BASE_DIR/books/non-fiction/business/business-book"
mkdir -p "$BASE_DIR/books/educational/textbooks/school-textbook"
mkdir -p "$BASE_DIR/books/educational/competitive/upsc-books"
mkdir -p "$BASE_DIR/books/children/story-books/fairy-tales"
mkdir -p "$BASE_DIR/books/children/activity/coloring-book"
mkdir -p "$BASE_DIR/stationery/notebooks/spiral-notebook"
mkdir -p "$BASE_DIR/stationery/notebooks/hardbound-diary"
mkdir -p "$BASE_DIR/stationery/pens/ballpoint-pen"
mkdir -p "$BASE_DIR/stationery/pens/gel-pen"
mkdir -p "$BASE_DIR/stationery/pens/fountain-pen"
mkdir -p "$BASE_DIR/stationery/pencils/pencil-pack"
mkdir -p "$BASE_DIR/stationery/pencils/mechanical-pencil"
mkdir -p "$BASE_DIR/stationery/office/stapler"
mkdir -p "$BASE_DIR/stationery/office/paper-a4"
mkdir -p "$BASE_DIR/stationery/office/file-folder"
mkdir -p "$BASE_DIR/stationery/school/geometry-box"
mkdir -p "$BASE_DIR/stationery/school/calculator"
mkdir -p "$BASE_DIR/stationery/school/school-bag"
mkdir -p "$BASE_DIR/stationery/art/color-pencils"
mkdir -p "$BASE_DIR/stationery/art/water-colors"
mkdir -p "$BASE_DIR/stationery/art/sketch-book"
mkdir -p "$BASE_DIR/stationery/accessories/glue-stick"
mkdir -p "$BASE_DIR/stationery/accessories/scissors"
mkdir -p "$BASE_DIR/stationery/accessories/tape"
mkdir -p "$BASE_DIR/stationery/accessories/eraser"

echo "✅ Successfully created 1000 product folders!"
echo "📁 Base directory: $BASE_DIR"
echo ""
echo "Summary:"
echo "- Fashion: 250 products"
echo "- Electronics: 150 products"
echo "- Food & Beverages: 150 products"
echo "- Grocery & Staples: 100 products"
echo "- Beauty & Personal Care: 100 products"
echo "- Home & Furniture: 100 products"
echo "- Sports & Fitness: 30 products"
echo "- Health & Medical: 30 products"
echo "- Jewelry: 30 products"
echo "- Footwear: 30 products"
echo "- Books & Stationery: 30 products"
echo ""
echo "Total: 1000 product folders created!"
echo ""
echo "Next steps for your team:"
echo "1. Navigate to each product folder"
echo "2. Add product image as 'main.jpg'"
echo "3. Optionally add more images: side.jpg, back.jpg, etc."