-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.business_categories (
  id text NOT NULL,
  name text NOT NULL,
  icon text,
  parent_category text,
  category_type text NOT NULL CHECK (category_type = ANY (ARRAY['main'::text, 'subcategory'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name character varying NOT NULL,
  icon character varying,
  subcategories ARRAY,
  created_at timestamp without time zone DEFAULT now(),
  category_type text,
  parent_business_category text,
  is_subcategory boolean DEFAULT false,
  parent_category_id uuid,
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_parent_category_id_fkey FOREIGN KEY (parent_category_id) REFERENCES public.categories(id),
  CONSTRAINT categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.completed_setups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name character varying,
  email character varying,
  phone character varying,
  business_name character varying,
  selected_goals jsonb,
  selected_categories jsonb,
  products_count integer DEFAULT 0,
  selected_theme character varying,
  qualifying_answers jsonb,
  lead_score integer DEFAULT 0,
  lead_quality character varying,
  setup_completed boolean DEFAULT true,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  selected_subcategories jsonb DEFAULT '[]'::jsonb,
  timeline text,
  budget_range text,
  decision_maker boolean DEFAULT false,
  online_presence text,
  CONSTRAINT completed_setups_pkey PRIMARY KEY (id),
  CONSTRAINT completed_setups_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.completion_actions (
  id integer NOT NULL DEFAULT nextval('completion_actions_id_seq'::regclass),
  user_id uuid,
  business_name text,
  selected_offer text,
  offer_id text,
  scheduled_slot text,
  reason_type text,
  comments text,
  action_type text NOT NULL,
  completion_choice text NOT NULL,
  scheduled_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  submitted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT completion_actions_pkey PRIMARY KEY (id),
  CONSTRAINT completion_actions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.crm_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  business_name text NOT NULL,
  phone text NOT NULL,
  address text,
  business_type text,
  business_category text,
  selected_goals ARRAY,
  goals_display ARRAY,
  goals_summary text,
  lead_score integer DEFAULT 0,
  lead_quality text DEFAULT 'Cold'::text,
  engagement_level text DEFAULT 'Low'::text,
  session_duration_minutes integer DEFAULT 0,
  device_type text,
  utm_source text,
  utm_campaign text,
  lead_status text DEFAULT 'New'::text,
  assigned_sdr_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  behavioral_data jsonb,
  source_data jsonb,
  timeline text,
  budget_range text,
  decision_maker boolean DEFAULT false,
  online_presence text,
  products_count integer DEFAULT 0,
  selected_categories jsonb DEFAULT '[]'::jsonb,
  selected_subcategories jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT crm_leads_pkey PRIMARY KEY (id)
);
CREATE TABLE public.followup_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  requested_followup boolean DEFAULT true,
  followup_type text DEFAULT 'free_setup_help'::text,
  requested_at timestamp with time zone DEFAULT now(),
  lead_status text DEFAULT 'Requested Followup'::text,
  contacted boolean DEFAULT false,
  contacted_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT followup_requests_pkey PRIMARY KEY (id),
  CONSTRAINT fk_followup_requests_user_id FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.lead_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  sdr_id uuid,
  comment_text text NOT NULL,
  comment_type text DEFAULT 'general'::text CHECK (comment_type = ANY (ARRAY['general'::text, 'call_log'::text, 'follow_up'::text, 'meeting'::text])),
  is_private boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_comments_pkey PRIMARY KEY (id),
  CONSTRAINT lead_comments_sdr_id_fkey FOREIGN KEY (sdr_id) REFERENCES public.sdr_users(id)
);
CREATE TABLE public.lead_intelligence (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  lead_score integer DEFAULT 0,
  lead_quality text DEFAULT 'Cold'::text,
  engagement_level text DEFAULT 'Low'::text,
  session_duration_minutes integer DEFAULT 0,
  page_views integer DEFAULT 1,
  form_completion_percentage numeric DEFAULT 0,
  time_on_language_screen integer DEFAULT 0,
  time_on_goals_screen integer DEFAULT 0,
  time_on_registration_screen integer DEFAULT 0,
  total_click_events integer DEFAULT 0,
  form_interactions_count integer DEFAULT 0,
  utm_source text DEFAULT 'Direct'::text,
  utm_medium text DEFAULT 'None'::text,
  utm_campaign text DEFAULT 'None'::text,
  utm_content text DEFAULT 'None'::text,
  utm_term text DEFAULT 'None'::text,
  device_type text DEFAULT 'Unknown'::text,
  browser text DEFAULT 'Unknown'::text,
  operating_system text DEFAULT 'Unknown'::text,
  screen_resolution text DEFAULT 'Unknown'::text,
  timezone text DEFAULT 'Unknown'::text,
  user_language text DEFAULT 'en'::text,
  selected_goals jsonb DEFAULT '[]'::jsonb,
  goals_display jsonb DEFAULT '[]'::jsonb,
  selected_language text DEFAULT 'en'::text,
  lead_status text DEFAULT 'New'::text,
  assigned_sdr_id uuid,
  ready_for_sdr_assignment boolean DEFAULT false,
  session_start_time timestamp with time zone DEFAULT now(),
  registration_completed_time timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  selected_main_categories jsonb DEFAULT '[]'::jsonb,
  selected_subcategories jsonb DEFAULT '[]'::jsonb,
  selected_categories jsonb,
  categories_count integer DEFAULT 0,
  subcategories_count integer DEFAULT 0,
  timeline text,
  budget_range text,
  decision_maker boolean DEFAULT false,
  online_presence text,
  lets_do_this_clicked boolean DEFAULT false,
  signup_completed boolean DEFAULT false,
  CONSTRAINT lead_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT lead_intelligence_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.lead_reasons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  selected_offer text,
  reason text,
  comments text,
  connection_type text DEFAULT 'more_details'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_reasons_pkey PRIMARY KEY (id),
  CONSTRAINT fk_lead_reasons_user_id FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  category_id uuid,
  name character varying NOT NULL,
  price numeric,
  description text,
  image_url character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  category_key character varying,
  subcategory_key character varying,
  is_custom boolean DEFAULT false,
  variants jsonb DEFAULT '[]'::jsonb,
  is_popular boolean DEFAULT false,
  suggested_price numeric,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.scheduled_calls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  selected_offer text,
  scheduled_datetime text,
  connection_type text DEFAULT 'team_call'::text,
  status text DEFAULT 'scheduled'::text,
  completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scheduled_calls_pkey PRIMARY KEY (id),
  CONSTRAINT fk_scheduled_calls_user_id FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.sdr_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  role text DEFAULT 'SDR'::text,
  is_active boolean DEFAULT true,
  current_leads integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sdr_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  phone character varying,
  business_name character varying,
  business_type character varying,
  business_category character varying,
  address text,
  selected_language character varying DEFAULT 'en'::character varying,
  selected_goals ARRAY,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  selected_categories jsonb,
  selected_subcategories jsonb,
  timeline text,
  budget_range text,
  decision_maker boolean DEFAULT false,
  online_presence text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);